# Generated by Django 5.0.3 on 2025-04-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("referral_services", "0003_alter_referralresult_result_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referraldoctor",
            name="referral_date",
        ),
        migrations.AlterField(
            model_name="referraldoctor",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="ReferralResult",
        ),
    ]
