# Generated by Django 5.0.3 on 2025-06-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "referral_services",
            "0006_alter_doctor_user2_alter_doctorspeciality_user2_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="user2",
        ),
        migrations.RemoveField(
            model_name="doctorspeciality",
            name="user2",
        ),
        migrations.RemoveField(
            model_name="referraldoctor",
            name="user2",
        ),
    ]
