# Generated by Django 5.0.3 on 2025-06-07 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "referral_services",
            "0007_remove_doctor_user2_remove_doctorspeciality_user2_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="referraldoctor",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_referral_doctors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
