# Generated by Django 5.0.3 on 2025-10-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("referral_services", "0008_referraldoctor_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctor",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="doctorspeciality",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="doctorspeciality",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="doctorspeciality",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="doctorspeciality",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="doctorspeciality",
            name="updated_at",
        ),
    ]
