# Generated by Django 5.0.3 on 2025-06-07 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_imaging", "0003_alter_medicalimagingcenter_user2_and_more"),
        ("patient", "0006_remove_appointment_user2_remove_patient_user2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalimagingcenter",
            name="user2",
        ),
        migrations.RemoveField(
            model_name="medicalimaginginsurance",
            name="user2",
        ),
        migrations.RemoveField(
            model_name="medicalimagingresult",
            name="user2",
        ),
        migrations.AlterField(
            model_name="medicalimagingresult",
            name="imaging_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="medical_imaging.medicalimagingcenter",
            ),
        ),
        migrations.AlterField(
            model_name="medicalimagingresult",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="patient.patient"
            ),
        ),
    ]
