# Generated by Django 5.0.3 on 2025-06-07 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_imaging", "0004_remove_medicalimagingcenter_user2_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalimagingresult",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_medical_imaging_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
