# Generated by Django 5.0.3 on 2025-10-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical_imaging", "0005_medicalimagingresult_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalimagingcenter",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="medicalimagingcenter",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="medicalimagingcenter",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="medicalimagingcenter",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="medicalimagingcenter",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="medicalimaginginsurance",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="medicalimaginginsurance",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="medicalimaginginsurance",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="medicalimaginginsurance",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="medicalimaginginsurance",
            name="updated_at",
        ),
    ]
