# Generated by Django 5.0.3 on 2025-04-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medical_imaging", "0001_initial"),
        ("medical_tests", "0001_initial"),
        ("medicines", "0001_initial"),
        ("other_paraclinic_services", "0001_initial"),
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("doctor_name", models.CharField(max_length=255)),
                ("clinic_address", models.CharField(max_length=100)),
                ("clinic_phone", models.CharField(max_length=100)),
                ("medical_education_number", models.CharField(max_length=100)),
                ("speciality", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Insulin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("short_acting", "Short Acting"),
                            ("long_acting", "Long Acting"),
                            ("None", "None"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicalImagingFavoriteGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicineAmount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("concept", models.CharField(max_length=300)),
                ("category", models.CharField(max_length=100)),
                ("tamin_json", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicineFavoriteGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicineInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("concept", models.CharField(max_length=300)),
                ("tamin_json", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicineRepeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("concept", models.CharField(max_length=300)),
                ("tamin_json", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicineUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("concept", models.CharField(max_length=300)),
                ("tamin_json", models.JSONField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="VisitPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("price", models.IntegerField(default=400000)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BMDRecordGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "major_osteoporotic_fracture_risk",
                    models.FloatField(blank=True, null=True),
                ),
                ("hip_fracture_risk", models.FloatField(blank=True, null=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bmd_records",
                        to="medical_imaging.medicalimagingcenter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BMDRecordItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parameter",
                    models.CharField(
                        choices=[("T_SCORE", "T_SCORE"), ("Z_SCORE", "Z_SCORE")],
                        max_length=255,
                    ),
                ),
                (
                    "site",
                    models.CharField(
                        choices=[
                            ("SPINE", "SPINE"),
                            ("FEMURAL_NECK_Right", "FEMURAL_NECK_RIGHT"),
                            ("FEMURAL_NECK_LEFT", "FEMURAL_NECK_LEFT"),
                            ("FEMURAL_NECK_MEAN", "FEMURAL_NECK_MEAN"),
                            ("TOTAL_HIP_RIGHT", "TOTAL_HIP_RIGHT"),
                            ("TOTAL_HIP_LEFT", "TOTAL_HIP_LEFT"),
                            ("TOTAL_HIP_MEAN", "TOTAL_HIP_MEAN"),
                            ("RADIUS", "RADIUS"),
                        ],
                        max_length=255,
                    ),
                ),
                ("value", models.FloatField()),
                ("bmd", models.FloatField()),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="visit.bmdrecordgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InsulinPrescriptionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InsulinPrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meal",
                    models.CharField(
                        choices=[
                            ("5AM", "5am"),
                            ("Morning", "m"),
                            ("Lunch", "l"),
                            ("Dinner", "d"),
                        ],
                        max_length=255,
                    ),
                ),
                ("dose", models.IntegerField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presc_items",
                        to="visit.insulinprescriptiongroup",
                    ),
                ),
                (
                    "insulin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="visit.insulin"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicalImagingFavoriteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="visit.medicalimagingfavoritegroup",
                    ),
                ),
                (
                    "imaging",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_imaging.medicalimaginginsurance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicalImagingPrescriptionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "tamin_tracking_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tamin_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalImagingPrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presc_items",
                        to="visit.medicalimagingprescriptiongroup",
                    ),
                ),
                (
                    "imaging",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_imaging.medicalimaginginsurance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicalImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="visit_medic_name_493763_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="MedicalTestFavoriteGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["name"], name="visit_medic_name_aba92a_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="MedicalTestFavoriteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="visit.medicaltestfavoritegroup",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_tests.medicaltestinsurance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicalTestPrescriptionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "tamin_tracking_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
                ("tamin_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalTestPrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presc_items",
                        to="visit.medicaltestprescriptiongroup",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medical_tests.medicaltestinsurance",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicinePrescriptionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "tamin_tracking_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tamin_id", models.CharField(blank=True, max_length=100, null=True)),
                ("tamin_response", models.JSONField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicinePrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("repeat_count", models.PositiveIntegerField(blank=True, null=True)),
                ("doDate", models.DateField(blank=True, null=True)),
                (
                    "amount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visit.medicineamount",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presc_items",
                        to="visit.medicineprescriptiongroup",
                    ),
                ),
                (
                    "instruction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visit.medicineinstruction",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicines.medicine",
                    ),
                ),
                (
                    "repeat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visit.medicinerepeat",
                    ),
                ),
                (
                    "usage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visit.medicineusage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MedicinePrescriptionFavoriteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "amount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visit.medicineamount",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="visit.medicinefavoritegroup",
                    ),
                ),
                (
                    "instruction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visit.medicineinstruction",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="medicines.medicine",
                    ),
                ),
                (
                    "usage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visit.medicineusage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OtherParaclinicServicesPrescriptionGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "tamin_tracking_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tamin_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtherParaclinicServicesPrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presc_items",
                        to="visit.otherparaclinicservicesprescriptiongroup",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="other_paraclinic_services.otherparaclinicservice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PatientHistoryBasic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("aspirin", models.BooleanField(blank=True, null=True)),
                ("statin", models.BooleanField(blank=True, null=True)),
                (
                    "ihd",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CABG", "CABG"),
                            ("STENT", "STENT"),
                            ("Angiography", "Angiography"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "retinopathy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Normal", "Normal"),
                            ("NPDR", "NPDR"),
                            ("PDR", "PDR"),
                            ("CSME", "CSME"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "right_amputation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Finger", "Finger"),
                            ("Sims", "Sims"),
                            ("Below-Knee", "Below-Knee"),
                            ("Ante-Knee", "Ante-Knee"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "left_amputation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Finger", "Finger"),
                            ("Sims", "Sims"),
                            ("Below-Knee", "Below-Knee"),
                            ("Ante-Knee", "Ante-Knee"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("gdm", models.BooleanField(blank=True, null=True)),
                ("radiation", models.BooleanField(blank=True, null=True)),
                ("thyroid_surgery", models.BooleanField(blank=True, null=True)),
                ("parathyroid_surgery", models.BooleanField(blank=True, null=True)),
                ("osteoprosis", models.BooleanField(blank=True, null=True)),
                (
                    "fracture",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Neck-Femur", "Neck-Femur"),
                            ("Lumbar-Spine", "Lumbar-Spine"),
                            ("Colles", "Colles"),
                            ("Other", "Other"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("esrd", models.BooleanField(blank=True, null=True)),
                (
                    "pituitary_radiation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gKnife", "gKnife"),
                            ("Conventional", "Conventional"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "alcohol",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Social", "Social"),
                            ("Regular", "Regular"),
                            ("Heavy", "Heavy"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("htn", models.BooleanField(blank=True, null=True)),
                ("hlp", models.BooleanField(blank=True, null=True)),
                (
                    "smoking",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Active", "Active"),
                            ("Passive", "Passive"),
                            ("Ex-smoker", "Ex-smoker"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("smoking_packes_per_year", models.IntegerField(blank=True, null=True)),
                ("blood_pressure_sys", models.IntegerField(blank=True, null=True)),
                ("blood_pressure_dias", models.IntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="basic_history",
                        to="patient.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientImpressionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "impression",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visit.medicalimpression",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("story", models.TextField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThyroidHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("is_normal", models.BooleanField(blank=True, null=True)),
                (
                    "thyroidectomy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Right", "Right"),
                            ("Left", "Left"),
                            ("Total", "Total"),
                            ("Subtotal", "Subtotal"),
                            ("Near_total", "Near Total"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("thyroidectomy_date", models.DateField(blank=True, null=True)),
                ("simple_goiter_gram", models.FloatField(blank=True, null=True)),
                ("mng_gram", models.FloatField(blank=True, null=True)),
                (
                    "mng_right_left",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Right > Left", "Right > Left"),
                            ("Left > Right", "Left > Right"),
                            ("Equal", "Equal"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "mng_largest_right_size_width",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "mng_largest_right_size_height",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "mng_largest_left_size_width",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "mng_largest_left_size_height",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("fee", models.IntegerField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitInsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(auto_now_add=True)),
                ("comment", models.TextField()),
                ("tamin_tracking_code", models.CharField(max_length=100)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="bmdrecordgroup",
            index=models.Index(
                fields=["patient"], name="visit_bmdre_patient_d87e9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalimagingprescriptiongroup",
            index=models.Index(
                fields=["patient"], name="visit_medic_patient_fba1d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicaltestprescriptiongroup",
            index=models.Index(
                fields=["patient", "code"], name="visit_medic_patient_415bd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicineprescriptiongroup",
            index=models.Index(
                fields=["patient", "tamin_id"], name="visit_medic_patient_0ccaa6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otherparaclinicservicesprescriptiongroup",
            index=models.Index(
                fields=["patient"], name="visit_other_patient_35ae3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patienthistorybasic",
            index=models.Index(
                fields=["patient"], name="visit_patie_patient_67086d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientimpressionitem",
            index=models.Index(
                fields=["patient"], name="visit_patie_patient_9e5736_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["patient"], name="visit_story_patient_e75817_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thyroidhistory",
            index=models.Index(
                fields=["patient"], name="visit_thyro_patient_152a7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["patient"], name="visit_visit_patient_b94adc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitinsurance",
            index=models.Index(
                fields=["patient"], name="visit_visit_patient_fd313a_idx"
            ),
        ),
    ]
