# Generated by Django 5.0.3 on 2025-04-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicineprescriptionitem",
            name="is_note",
            field=models.BooleanField(default=False),
        ),
    ]
