# Generated by Django 5.0.3 on 2025-04-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visit", "0002_medicineprescriptionitem_is_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="bmdrecorditem",
            name="delta_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
