# Generated by Django 5.0.3 on 2025-05-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visit", "0004_otherparaclinicfavoritegroup_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="otherparaclinicfavoriteitem",
            old_name="item",
            new_name="service",
        ),
    ]
