# Generated by Django 5.0.3 on 2025-05-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visit", "0005_rename_item_otherparaclinicfavoriteitem_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientimpressionitem",
            name="date",
            field=models.DateField(),
        ),
    ]
