# Generated by Django 5.0.3 on 2025-06-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visit", "0010_bmdrecordgroup_created_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalimpression",
            name="created_by",
        ),
    ]
