# Generated by Django 5.0.3 on 2025-09-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visit", "0011_remove_medicalimpression_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmdrecorditem",
            name="site",
            field=models.CharField(
                choices=[
                    ("SPINE", "SPINE"),
                    ("FEMURAL_NECK_RIGHT", "FEMURAL_NECK_RIGHT"),
                    ("FEMURAL_NECK_LEFT", "FEMURAL_NECK_LEFT"),
                    ("FEMURAL_NECK_MEAN", "FEMURAL_NECK_MEAN"),
                    ("TOTAL_HIP_RIGHT", "TOTAL_HIP_RIGHT"),
                    ("TOTAL_HIP_LEFT", "TOTAL_HIP_LEFT"),
                    ("TOTAL_HIP_MEAN", "TOTAL_HIP_MEAN"),
                    ("RADIUS", "RADIUS"),
                ],
                max_length=255,
            ),
        ),
    ]
