# Generated by Django 5.0.3 on 2025-10-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visit", "0012_alter_bmdrecorditem_site"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinicdata",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="clinicdata",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="clinicdata",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="clinicdata",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="clinicdata",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="insulin",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="insulin",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="insulin",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="insulin",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="insulin",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="medicalimpression",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="medicalimpression",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="medicalimpression",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="medicalimpression",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="medicalimpression",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="visitprice",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="visitprice",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="visitprice",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="visitprice",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="visitprice",
            name="updated_at",
        ),
    ]
