# Generated by Django 5.0.3 on 2025-10-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("visit", "0013_remove_clinicdata_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicineamount",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="medicineamount",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="medicineamount",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="medicineamount",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="medicineamount",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="medicineinstruction",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="medicineinstruction",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="medicineinstruction",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="medicineinstruction",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="medicineinstruction",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="medicinerepeat",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="medicinerepeat",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="medicinerepeat",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="medicinerepeat",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="medicinerepeat",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="medicineusage",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="medicineusage",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="medicineusage",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="medicineusage",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="medicineusage",
            name="updated_at",
        ),
    ]
