# Generated by Django 5.0.3 on 2025-09-20 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0005_appointmentslot_created_by"),
        ("patient", "0008_appointment_created_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "authority",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("ref_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("PENDING_VERIFY", "Pending Verify"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                ("is_sandbox", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="appointmentslot",
            index=models.Index(
                fields=["patient"], name="appointment_patient_3b4a42_idx"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="patient.patient"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="appointment.appointmentslot",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["authority"], name="appointment_authori_5d9c9d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymenttransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["INITIATED", "PENDING_VERIFY"])),
                fields=("slot",),
                name="uniq_active_payment_per_slot",
            ),
        ),
    ]
