# Generated by Django 5.0.3 on 2025-10-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0006_paymenttransaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="transaction_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
