# Generated by Django 5.0.3 on 2025-11-04 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_paymenttransaction_deleted_at_and_more'),
        ('patient', '0009_preregisterpatient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='pre_registered_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.preregisterpatient'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='pre_registered_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.preregisterpatient'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patient.patient'),
        ),
    ]
