# Generated by Django 5.0.3 on 2025-04-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, null=True)),
                ("last_name", models.CharField(blank=True, max_length=150, null=True)),
                ("address", models.TextField(blank=True, max_length=255, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("telephone", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "refferal_reason",
                    models.TextField(blank=True, max_length=255, null=True),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("referer", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "education",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("illiterate", "illiterate"),
                            ("elementary", "elementary"),
                            ("middle_school", "middle_school"),
                            ("high_school", "high_school"),
                            ("diploma", "diploma"),
                            ("associate", "associate"),
                            ("bachelor", "bachelor"),
                            ("master", "master"),
                            ("phd", "phd"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("occupation", models.CharField(blank=True, max_length=255, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                (
                    "insurance_company",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bank", "bank"),
                            ("sedasima", "sedasima"),
                            ("military", "military"),
                            ("azad", "azad"),
                            ("shahrdari", "shahrdari"),
                            ("salamat", "salamat"),
                            ("tamin", "tamin"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("next_visit_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["national_id", "phone_number"],
                        name="patient_pat_nationa_e9cce5_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("datetime", models.DateTimeField()),
                (
                    "description",
                    models.TextField(blank=True, max_length=511, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Confirmed", "Confirmed"),
                            ("Canceld_by_patient", "Canceled_by_patient"),
                            ("Canceled_by_secretary", "Canceled_by_secretary"),
                            ("Done", "Done"),
                        ],
                        default="Confirmed",
                        max_length=255,
                    ),
                ),
                ("canceled_at", models.DateField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patient.patient",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["datetime"], name="patient_app_datetim_bb02df_idx"
                    )
                ],
            },
        ),
    ]
