# Generated by Django 5.0.3 on 2025-04-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="insurance_company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
