# Generated by Django 5.0.3 on 2025-04-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0002_alter_patient_insurance_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="canceled_at",
        ),
        migrations.AlterField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Visiting", "Visiting"),
                    ("Canceled_by_patient", "Canceled_by_patient"),
                    ("Canceled_by_secretary", "Canceled_by_secretary"),
                    ("Visited", "Visited"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
    ]
