# Generated by Django 5.0.3 on 2025-06-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0005_alter_appointment_user2_alter_patient_user2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="user2",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="user2",
        ),
    ]
