# Generated by Django 5.0.3 on 2025-11-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_appointment_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegisterPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=512, null=True)),
                ('last_name', models.CharField(blank=True, max_length=512, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
