# Generated by Django 5.0.3 on 2025-11-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_preregisterpatient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='updated_at',
        ),
    ]
