# Generated by Django 5.0.3 on 2025-06-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("other_paraclinic_services", "0003_alter_category_user2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="user2",
        ),
        migrations.RemoveField(
            model_name="otherparaclinicservice",
            name="user2",
        ),
    ]
