# Generated by Django 5.0.3 on 2025-10-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("other_paraclinic_services", "0004_remove_category_user2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="category",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="category",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="category",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="category",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="otherparaclinicservice",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="otherparaclinicservice",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="otherparaclinicservice",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="otherparaclinicservice",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="otherparaclinicservice",
            name="updated_at",
        ),
    ]
