# Generated by Django 5.0.3 on 2025-05-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_tests", "0002_testmetricgroup_testmetric_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testmetric",
            name="group",
        ),
        migrations.AddField(
            model_name="testmetric",
            name="group_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="TestMetricGroup",
        ),
    ]
