# Generated by Django 5.0.3 on 2025-05-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medical_tests",
            "0003_remove_testmetric_group_testmetric_group_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="testmetric",
            name="group_name",
            field=models.CharField(default="Other", max_length=255),
        ),
    ]
