# Generated by Django 5.0.3 on 2025-06-07 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_tests", "0006_alter_laboratory_user2_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laboratory",
            name="user2",
        ),
        migrations.RemoveField(
            model_name="medicaltestinsurance",
            name="user2",
        ),
        migrations.RemoveField(
            model_name="metricunit",
            name="user2",
        ),
        migrations.RemoveField(
            model_name="testmetric",
            name="user2",
        ),
        migrations.RemoveField(
            model_name="testresultfavoritegroup",
            name="user2",
        ),
        migrations.RemoveField(
            model_name="testresultgroup",
            name="user2",
        ),
        migrations.RemoveField(
            model_name="testresultitem",
            name="user2",
        ),
        migrations.AlterField(
            model_name="testmetric",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="medical_tests.metricunit",
            ),
        ),
        migrations.AlterField(
            model_name="testresultitem",
            name="metric",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="result_items",
                to="medical_tests.testmetric",
            ),
        ),
    ]
