# Generated by Django 5.0.3 on 2025-10-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medical_tests", "0008_testresultgroup_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laboratory",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="laboratory",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="laboratory",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="laboratory",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="laboratory",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="metricunit",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="metricunit",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="metricunit",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="metricunit",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="metricunit",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="testmetric",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="testmetric",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="testmetric",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="testmetric",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="testmetric",
            name="updated_at",
        ),
    ]
