# Generated by Django 5.0.3 on 2025-06-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("paraclinic", "0003_alter_paraclinicresult_user2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paraclinicresult",
            name="user2",
        ),
    ]
