# Generated by Django 5.0.3 on 2025-04-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("transaction_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=511)),
                ("category", models.CharField(default="None", max_length=255)),
                ("is_insured", models.BooleanField(default=False)),
                ("tamin_json", models.JSONField(blank=True, null=True)),
                ("tamin_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("code", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["name", "tamin_id"], name="medicines_m_name_a131c5_idx"
                    )
                ],
            },
        ),
    ]
