# Generated by Django 5.0.3 on 2025-06-07 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0003_alter_medicine_user2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="user2",
        ),
    ]
