# Generated by Django 5.0.3 on 2025-10-05 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("medicines", "0004_remove_medicine_user2"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicine",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="restored_at",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="transaction_id",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="updated_at",
        ),
    ]
