# Generated by Django 5.0.3 on 2025-10-03 03:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmessage',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
