# Generated by Django 5.0.3 on 2025-10-03 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messages', '0002_alter_appmessage_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmessage',
            name='users_read',
            field=models.ManyToManyField(blank=True, null=True, related_name='app_messages_read', to=settings.AUTH_USER_MODEL),
        ),
    ]
